# Development Frontend Dockerfile
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY client/package*.json ./client/

RUN npm install
RUN cd client && npm install

COPY client/ ./client/

EXPOSE 3000
EXPOSE 5173

CMD ["npm", "run", "dev:client"]
